version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0
  node: circleci/node@4.1.0
  slack: circleci/slack@4.4.4

commands:
  setup-env-vars:
    steps:
      - run: chmod +x .circleci/env-setup.sh && .circleci/env-setup.sh
  deploy-app:
    steps:
      - install-packages
      - run: npm run deploy
  install-packages:
    steps:
      - run: npm install

jobs:
  test-client:
    executor: node/default
    steps:
      - checkout
      - setup-env-vars
      - install-packages
      - run: npm run test
  deploy:
    executor: aws-cli/default
    #    resource_class: medium+
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - aws-cli/setup
      - setup-env-vars
      - deploy-app
      - slack/notify:
          event: pass
          custom: |
            {
            	"text": "CircleCI job succeeded!",
            	"blocks": [
            		{
            			"type": "header",
            			"text": {
            				"type": "plain_text",
            				"text": "Job Succeeded. :white_check_mark:",
            				"emoji": true
            			}
            		},
            		{
            			"type": "section",
            			"fields": [
            				{
            					"type": "mrkdwn",
            					"text": "*Job*: ${CIRCLE_JOB}"
            				}
            			]
            		},
            		{
            			"type": "section",
            			"fields": [
            				{
            					"type": "mrkdwn",
            					"text": "*Project*:\n $CIRCLE_PROJECT_REPONAME"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Branch*:\n $CIRCLE_BRANCH"
                            },
                            {
            					"type": "mrkdwn",
            					"text": "*Message*:\n $(git log --format=format:"%s" -n 1 $CIRCLE_SHA1)"
            				},
            				{
            					"type": "mrkdwn",
            					"text": "*Author*:\n $CIRCLE_USERNAME"
            				}
            			],
            			"accessory": {
            				"type": "image",
            				"image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
            				"alt_text": "CircleCI logo"
            			}
            		},
            		{
            			"type": "actions",
            			"elements": [
            				{
            					"type": "button",
            					"text": {
            						"type": "plain_text",
            						"text": "View Job"
            					},
            					"url": "${CIRCLE_BUILD_URL}"
            				}
            			]
            		}
            	]
            }

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-client:
          context:
            - tidepool-npm #should be specified on circleci
      - deploy:
          context:
            - aws-account #should be specified on circleci
            - tidepool-npm #should be specified on circleci
            - slack-secrets #should be specified on circleci
          requires:
            - test-client
          filters:
            branches:
              only:
                - develop
                - staging
                - master
                - deploy
